### ISSUE TITLE
doesn't save preferences for each software

### ISSUE THREAD

**Issue by mantrasiva** [AlexanderPro/SmartSystemMenu#26] opened 2021-03-01 06:20 UTC
Hi
I love this program but it does't save preferences for each software
is there a way to do it?
could be added?
thanks

**Comment by netsonicyxf** [comment] 2021-05-09 12:26
Yes, I want this "save preferences for each software" too

**Comment by AlexanderPro** [comment] 2022-04-10 17:15
Duplicate of #61

**Closed by AlexanderPro** 2022-04-10 17:16 UTC
