### ISSUE TITLE
[Feature Request] Remember different settings for different apps

### ISSUE THREAD

**Issue by netsonicyxf** [AlexanderPro/SmartSystemMenu#57] opened 2022-01-11 14:39 UTC
For example, I want to apply "always minimize to tray" to X1 app, 
and apply "always on top" to X2 app.
when SSM launches.
and I can temporarily disable these settings.

**Comment by netsonicyxf** [comment] 2022-01-22 03:03
But there is no feature in the SSM to remember these settings for apps

**Comment by AlexanderPro** [comment] 2022-01-22 05:33
Hi netsonicyxf,

I am going to add this feature in the next versions.

**Comment by netsonicyxf** [comment] 2022-01-22 05:35
Hi Alexander，

Looking forward to see the next version.
Thank you!

**Comment by AlexanderPro** [comment] 2022-04-10 17:16
Duplicate of #61

**Closed by AlexanderPro** 2022-04-10 17:16 UTC
